const fs=require('fs');const s=fs.readFileSync('resources/js/Pages/SuperAdmin/RestaurantSettings.jsx','utf8');function lineOfIndex(idx){return s.slice(0,idx).split('\n').length;}function findTagAt(pos){ const n=s.length; let i=pos+1; if(i>=n) return null; if(s[i]==='/'){ i++; let name=''; while(i<n && /[A-Za-z0-9_:\.]/.test(s[i])){ name+=s[i++]; } return {type:'close', name, start:pos, end:i}; } else if(s[i]==='!'){ return null; } else { let name=''; while(i<n && /[A-Za-z0-9_:\.]/.test(s[i])){ name+=s[i++]; } return {type:'open', name, start:pos, end:i}; }}
let i=0;const stack=[];const mismatches=[];while(i<s.length){ if(s[i]==='<'){ const tag=findTagAt(i); if(!tag){ i++; continue; } let j=i+1; let inSq=false,inDq=false,inTpl=false,inExpr=0; let gt=-1; for(j=i+1;j<s.length;j++){ const ch=s[j]; if(ch==="'" && !inDq && !inTpl) inSq=!inSq; else if(ch==='"' && !inSq && !inTpl) inDq=!inDq; else if(ch==='`' && !inSq && !inDq) inTpl=!inTpl; else if(ch==='{' && !inSq && !inDq && !inTpl) inExpr++; else if(ch==='}' && !inSq && !inDq && !inTpl){ if(inExpr>0) inExpr--; } else if(ch==='>' && !inSq && !inDq && !inTpl && inExpr===0){ gt=j; break; }} if(gt===-1){ console.log('No closing > for tag starting at line',lineOfIndex(i)); break;} const isSelfClose = s[gt-1]==='/' || s[gt-1]==='?'; const tagname=tag.name||''; const l=lineOfIndex(i); if(tag.type==='open'){ if(!isSelfClose){ stack.push({name:tagname,line:l,start:i}); } } else if(tag.type==='close'){ if(stack.length===0){ mismatches.push({type:'unmatchedClose',tag:tagname,line:l}); } else { let last=stack[stack.length-1]; if(last.name===tagname){ stack.pop(); } else { // mismatched: try to find matching open deeper in stack
        let foundIdx=-1; for(let k=stack.length-1;k>=0;k--){ if(stack[k].name===tagname){ foundIdx=k; break; } }
        if(foundIdx===-1){ mismatches.push({type:'mismatch', expected:last.name, found:tagname, line:l, stackTop:stack.slice(-5)}); // ignore this close
        } else { // pop until foundIdx
            const popped=stack.splice(foundIdx); mismatches.push({type:'autoPopped',popped,line:l}); }
     } }
    }
    i=gt+1; continue; }
 i++; }
console.log('Scan complete. Remaining unclosed tags (bottom->top):'); stack.forEach(x=>console.log(x.name,'opened at line',x.line)); console.log('MISMATCHES:', mismatches); fs.writeFileSync('tmp_jsx_stack.json',JSON.stringify({stack,mismatches},null,2)); console.log('Details in tmp_jsx_stack.json');
